[server]
control_plane ansible_host=4.223.110.248 private_ip=10.0.1.4

[agents]
worker_0 ansible_host=20.91.197.134 private_ip=10.0.1.5
worker_1 ansible_host=51.12.86.216 private_ip=10.0.1.6

[k3s_cluster:children]
server
agents