apiVersion: batch/v1
kind: Job
metadata:
  name: taskapp-migrate
  namespace: taskapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:16.14
          command: ["sh", "-c", "until pg_isready -h postgres.taskapp.svc.cluster.local -p 5432 -U postgres; do echo 'waiting for postgres...'; sleep 2; done"]
      containers:
        - name: migrate
          image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc
          command: ["sh", "-c", "alembic upgrade head"]

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

